/**
 * Auths Actions - Auths Domain (Refactored)
 *
 * Refactored to use common CRUD patterns with domain-specific custom actions.
 * This demonstrates how to combine common actions with domain-specific functionality.
 */

import { DomainActions } from "../types";
import { generateServiceCRUDActions } from "./utils";

// Common Actions
const SVC_AUTH_ACCOUNTS_CRUD_ACTIONS = generateServiceCRUDActions([
  { serviceName: "SVC_AUTH_ACCOUNTS", entity: "ACCOUNT" },
]);

// Custom Actions
export const SVC_AUTH_AUTHENTICATIONS: DomainActions = {
  ACTION_LOGIN: "ACTION_LOGIN",
  ACTION_LOGOUT: "ACTION_LOGOUT",
  ACTION_REFRESH_TOKEN: "ACTION_REFRESH_TOKEN",
  ACTION_VERIFY_JWT_TOKEN: "ACTION_VERIFY_JWT_TOKEN",
  ACTION_SAVE_DEVICE_TOKEN: "ACTION_SAVE_DEVICE_TOKEN",
};

export const SVC_AUTH_AUTHORIZATIONS_TENANT_ROLE: DomainActions = {
  ACTION_GET_TENANT_ROLES: "ACTION_GET_TENANT_ROLES",
  ACTION_DELETE_TENANT_ROLES: "ACTION_DELETE_TENANT_ROLES",
  ACTION_CREATE_TENANT_ROLES: "ACTION_CREATE_TENANT_ROLES",
  ACTION_UPDATE_TENANT_ROLES: "ACTION_UPDATE_TENANT_ROLES",
  ACTION_GET_APPLICATION_ACTIONS: "ACTION_GET_APPLICATION_ACTIONS",
  ACTION_UPDATE_MANY_TENANT_ROLES: "ACTION_UPDATE_MANY_TENANT_ROLES",
};

export const SVC_AUTH_ACCOUNTS: DomainActions = {
  ...SVC_AUTH_ACCOUNTS_CRUD_ACTIONS,
  // ACCOUNT - Custom actions
  ACTION_VERIFY_ACCOUNT: "ACTION_VERIFY_ACCOUNT",
  ACTION_RESET_PASSWORD: "ACTION_RESET_PASSWORD",
  ACTION_CHANGE_PASSWORD: "ACTION_CHANGE_PASSWORD",
  ACTION_DELETE_ACCOUNTS: "ACTION_DELETE_ACCOUNTS",
  ACTION_FORGOT_PASSWORD: "ACTION_FORGOT_PASSWORD",
  ACTION_GET_LIST_ACCOUNT: "ACTION_GET_LIST_ACCOUNT",
  ACTION_GET_DETAIL_ACCOUNT: "ACTION_GET_DETAIL_ACCOUNT",
  ACTION_UPDATE_ACCOUNT_STATUS: "ACTION_UPDATE_ACCOUNT_STATUS",
  ACTION_RESEND_ACCOUNT_MAIL_CONFIRM: "ACTION_RESEND_ACCOUNT_MAIL_CONFIRM",
  ACTION_SEND_ACCOUNT_MAIL_DEACTIVATED: "ACTION_SEND_ACCOUNT_MAIL_DEACTIVATED",
};
