/**
 * Business Permissions - BUSINESS Domain
 *
 * Simple, performance-optimized permission constants for business domain.
 * All permissions follow the KEY: "value" format for maximum performance.
 */

import { DomainPermissions } from "../types";

/**
 * Business Permissions
 *
 * Contains all business-related permissions as simple string constants.
 * This provides maximum performance with zero runtime overhead.
 */
export const BUSINESS_PERMISSIONS: DomainPermissions = {
  // User Management Permissions
  BUSINESS_CREATE_USER: "BUSINESS_CREATE_USER",
  BUSINESS_UPDATE_USER: "BUSINESS_UPDATE_USER",
  BUSINESS_DELETE_USER: "BUSINESS_DELETE_USER",
  BUSINESS_GET_USER: "BUSINESS_GET_USER",
  BUSINESS_LIST_USERS: "BUSINESS_LIST_USERS",
  BUSINESS_ASSIGN_ROLE: "BUSINESS_ASSIGN_ROLE",
  BUSINESS_REMOVE_ROLE: "BUSINESS_REMOVE_ROLE",

  // Role Management Permissions
  BUSINESS_CREATE_ROLE: "BUSINESS_CREATE_ROLE",
  BUSINESS_UPDATE_ROLE: "BUSINESS_UPDATE_ROLE",
  BUSINESS_DELETE_ROLE: "BUSINESS_DELETE_ROLE",
  BUSINESS_GET_ROLE: "BUSINESS_GET_ROLE",
  BUSINESS_LIST_ROLES: "BUSINESS_LIST_ROLES",

  // Permission Management Permissions
  BUSINESS_CREATE_PERMISSION: "BUSINESS_CREATE_PERMISSION",
  BUSINESS_UPDATE_PERMISSION: "BUSINESS_UPDATE_PERMISSION",
  BUSINESS_DELETE_PERMISSION: "BUSINESS_DELETE_PERMISSION",
  BUSINESS_GET_PERMISSION: "BUSINESS_GET_PERMISSION",
  BUSINESS_LIST_PERMISSIONS: "BUSINESS_LIST_PERMISSIONS",
  BUSINESS_ASSIGN_PERMISSION: "BUSINESS_ASSIGN_PERMISSION",
  BUSINESS_REMOVE_PERMISSION: "BUSINESS_REMOVE_PERMISSION",

  // Tenant Management Permissions
  BUSINESS_CREATE_TENANT: "BUSINESS_CREATE_TENANT",
  BUSINESS_UPDATE_TENANT: "BUSINESS_UPDATE_TENANT",
  BUSINESS_DELETE_TENANT: "BUSINESS_DELETE_TENANT",
  BUSINESS_GET_TENANT: "BUSINESS_GET_TENANT",
  BUSINESS_LIST_TENANTS: "BUSINESS_LIST_TENANTS",

  // Settings Management Permissions
  BUSINESS_UPDATE_SETTINGS: "BUSINESS_UPDATE_SETTINGS",
  BUSINESS_GET_SETTINGS: "BUSINESS_GET_SETTINGS",
  BUSINESS_RESET_SETTINGS: "BUSINESS_RESET_SETTINGS",

  // Audit Management Permissions
  BUSINESS_GET_AUDIT_LOGS: "BUSINESS_GET_AUDIT_LOGS",
  BUSINESS_EXPORT_AUDIT_LOGS: "BUSINESS_EXPORT_AUDIT_LOGS",
  BUSINESS_CLEAR_AUDIT_LOGS: "BUSINESS_CLEAR_AUDIT_LOGS",
} as const;
