/**
 * Inventory Permissions - INVENTORY Domain
 *
 * Simple, performance-optimized permission constants for inventory domain.
 * All permissions follow the KEY: "value" format for maximum performance.
 */

import { DomainPermissions } from "../types";

/**
 * Inventory Permissions
 *
 * Contains all inventory-related permissions as simple string constants.
 * This provides maximum performance with zero runtime overhead.
 */
export const INVENTORY_PERMISSIONS: DomainPermissions = {
  // Product Management Permissions
  INVENTORY_CREATE_PRODUCT: "INVENTORY_CREATE_PRODUCT",
  INVENTORY_UPDATE_PRODUCT: "INVENTORY_UPDATE_PRODUCT",
  INVENTORY_DELETE_PRODUCT: "INVENTORY_DELETE_PRODUCT",
  INVENTORY_GET_PRODUCT: "INVENTORY_GET_PRODUCT",
  INVENTORY_LIST_PRODUCTS: "INVENTORY_LIST_PRODUCTS",
  INVENTORY_SEARCH_PRODUCTS: "INVENTORY_SEARCH_PRODUCTS",

  // Stock Management Permissions
  INVENTORY_ADD_STOCK: "INVENTORY_ADD_STOCK",
  INVENTORY_REMOVE_STOCK: "INVENTORY_REMOVE_STOCK",
  INVENTORY_ADJUST_STOCK: "INVENTORY_ADJUST_STOCK",
  INVENTORY_GET_STOCK: "INVENTORY_GET_STOCK",
  INVENTORY_LIST_STOCK: "INVENTORY_LIST_STOCK",
  INVENTORY_CHECK_STOCK: "INVENTORY_CHECK_STOCK",

  // Category Management Permissions
  INVENTORY_CREATE_CATEGORY: "INVENTORY_CREATE_CATEGORY",
  INVENTORY_UPDATE_CATEGORY: "INVENTORY_UPDATE_CATEGORY",
  INVENTORY_DELETE_CATEGORY: "INVENTORY_DELETE_CATEGORY",
  INVENTORY_GET_CATEGORY: "INVENTORY_GET_CATEGORY",
  INVENTORY_LIST_CATEGORIES: "INVENTORY_LIST_CATEGORIES",

  // Supplier Management Permissions
  INVENTORY_CREATE_SUPPLIER: "INVENTORY_CREATE_SUPPLIER",
  INVENTORY_UPDATE_SUPPLIER: "INVENTORY_UPDATE_SUPPLIER",
  INVENTORY_DELETE_SUPPLIER: "INVENTORY_DELETE_SUPPLIER",
  INVENTORY_GET_SUPPLIER: "INVENTORY_GET_SUPPLIER",
  INVENTORY_LIST_SUPPLIERS: "INVENTORY_LIST_SUPPLIERS",

  // Purchase Order Permissions
  INVENTORY_CREATE_PURCHASE_ORDER: "INVENTORY_CREATE_PURCHASE_ORDER",
  INVENTORY_UPDATE_PURCHASE_ORDER: "INVENTORY_UPDATE_PURCHASE_ORDER",
  INVENTORY_DELETE_PURCHASE_ORDER: "INVENTORY_DELETE_PURCHASE_ORDER",
  INVENTORY_GET_PURCHASE_ORDER: "INVENTORY_GET_PURCHASE_ORDER",
  INVENTORY_LIST_PURCHASE_ORDERS: "INVENTORY_LIST_PURCHASE_ORDERS",
  INVENTORY_APPROVE_PURCHASE_ORDER: "INVENTORY_APPROVE_PURCHASE_ORDER",
  INVENTORY_RECEIVE_PURCHASE_ORDER: "INVENTORY_RECEIVE_PURCHASE_ORDER",

  // Report Permissions
  INVENTORY_GENERATE_STOCK_REPORT: "INVENTORY_GENERATE_STOCK_REPORT",
  INVENTORY_GENERATE_MOVEMENT_REPORT: "INVENTORY_GENERATE_MOVEMENT_REPORT",
  INVENTORY_GENERATE_LOW_STOCK_REPORT: "INVENTORY_GENERATE_LOW_STOCK_REPORT",
  INVENTORY_GENERATE_EXPIRY_REPORT: "INVENTORY_GENERATE_EXPIRY_REPORT",
} as const;
