/**
 * Sales Permissions - SALES Domain
 *
 * Simple, performance-optimized permission constants for sales domain.
 * All permissions follow the KEY: "value" format for maximum performance.
 */

import { DomainPermissions } from "../types";

/**
 * Sales Permissions
 *
 * Contains all sales-related permissions as simple string constants.
 * This provides maximum performance with zero runtime overhead.
 */
export const SALES_PERMISSIONS: DomainPermissions = {
  // Order Management Permissions
  SALES_CREATE_ORDER: "SALES_CREATE_ORDER",
  SALES_UPDATE_ORDER: "SALES_UPDATE_ORDER",
  SALES_DELETE_ORDER: "SALES_DELETE_ORDER",
  SALES_GET_ORDER: "SALES_GET_ORDER",
  SALES_LIST_ORDERS: "SALES_LIST_ORDERS",
  SALES_APPROVE_ORDER: "SALES_APPROVE_ORDER",
  SALES_REJECT_ORDER: "SALES_REJECT_ORDER",
  SALES_CANCEL_ORDER: "SALES_CANCEL_ORDER",

  // Payment Processing Permissions
  SALES_PROCESS_PAYMENT: "SALES_PROCESS_PAYMENT",
  SALES_REFUND_PAYMENT: "SALES_REFUND_PAYMENT",
  SALES_VOID_PAYMENT: "SALES_VOID_PAYMENT",
  SALES_GET_PAYMENT: "SALES_GET_PAYMENT",
  SALES_LIST_PAYMENTS: "SALES_LIST_PAYMENTS",

  // Customer Management Permissions
  SALES_CREATE_CUSTOMER: "SALES_CREATE_CUSTOMER",
  SALES_UPDATE_CUSTOMER: "SALES_UPDATE_CUSTOMER",
  SALES_DELETE_CUSTOMER: "SALES_DELETE_CUSTOMER",
  SALES_GET_CUSTOMER: "SALES_GET_CUSTOMER",
  SALES_LIST_CUSTOMERS: "SALES_LIST_CUSTOMERS",

  // Invoice Management Permissions
  SALES_CREATE_INVOICE: "SALES_CREATE_INVOICE",
  SALES_UPDATE_INVOICE: "SALES_UPDATE_INVOICE",
  SALES_DELETE_INVOICE: "SALES_DELETE_INVOICE",
  SALES_GET_INVOICE: "SALES_GET_INVOICE",
  SALES_LIST_INVOICES: "SALES_LIST_INVOICES",
  SALES_SEND_INVOICE: "SALES_SEND_INVOICE",

  // Discount Management Permissions
  SALES_CREATE_DISCOUNT: "SALES_CREATE_DISCOUNT",
  SALES_UPDATE_DISCOUNT: "SALES_UPDATE_DISCOUNT",
  SALES_DELETE_DISCOUNT: "SALES_DELETE_DISCOUNT",
  SALES_GET_DISCOUNT: "SALES_GET_DISCOUNT",
  SALES_LIST_DISCOUNTS: "SALES_LIST_DISCOUNTS",
  SALES_APPLY_DISCOUNT: "SALES_APPLY_DISCOUNT",
} as const;
